"""Provider-neutral context economics / session efficiency measurement layer.

This subpackage answers: how efficiently is an AI runtime using context, and
what does the data suggest? It is independent of any single orchestrator
(Agent Crew or otherwise) and works from raw Claude/Codex/Gemini telemetry
even when no orchestrator-level attribution is present.

See ``docs/context-economics.md`` for the full public contract.
"""

from __future__ import annotations

from .analytics import (
    PARTIAL_UNKNOWN_FAILURE_CAUSE_RATE_THRESHOLD,
    PARTIAL_UNKNOWN_FAILURE_CAUSE_WARNING,
    UNKNOWN_FAILURE_CAUSE_WARNING,
    cache_creation_per_successful_task,
    cache_read_per_task,
    compare_context_policies,
    context_policy_cohort,
    context_age_vs_failure_rate,
    context_age_vs_token_usage,
    failed_retry_token_waste,
    fresh_input_per_successful_task,
    lock_wait_summary,
    provider_context_by_policy,
    provider_context_window_summary,
    stratified_failure_rates,
    test_treatment_cohorts,
    test_treatment_failure_rates,
    tokens_per_outcome,
    tokens_per_successful_task,
    unknown_cause_warning,
    context_window_observations,
    task_token_telemetry_summary,
    task_telemetry_by_stable_prefix,
)
from .compact_analysis import before_after_compact
from .context_pack_analytics import (
    context_composition,
    context_pack_efficiency,
    retrieval_mode_comparison,
)
from .correlate import (
    ProviderUsageRecord,
    attach_provider_context_observations,
    attach_provider_context_clearings,
    correlate_task_economics,
)
from .agent_crew_adapter import (
    context_pack_attributions_from_events,
    reconcile_attribution_by_task,
    test_stage_deferrals_for_task,
)
from .schema import (
    SCHEMA_VERSION,
    ContextLifecycleEvent,
    ContextPackAttribution,
    ContextPolicy,
    FailureCategory,
    LifecycleEventType,
    NormalizedOutcome,
    RuntimeAttribution,
    TaskEconomicsRecord,
    TokenComponents,
    attribution_from_dict,
    attribution_to_dict,
    classify_failure_category,
    context_pack_attribution_from_event,
    ProviderContextObservation,
    ProviderContextClearing,
    provider_context_observation_from_event,
    provider_context_clearing_from_event,
    provider_context_clearings_from_events,
    provider_context_observations_from_events,
    extract_failure_reason,
    infer_retryable,
    lifecycle_event_from_dict,
    lifecycle_event_to_dict,
    normalize_outcome,
    parse_flexible_timestamp,
    task_economics_to_dict,
    token_components_from_dict,
    token_components_to_dict,
    token_components_total,
    validate_attribution_dict,
    TaskTokenTelemetry,
    TASK_TOKEN_TELEMETRY_FIELDS,
    TASK_ATTRIBUTION_HASH_FIELDS,
    task_token_telemetry_from_dict,
    task_token_telemetry_to_dict,
)
from .token_components import (
    claude_token_components,
    codex_token_components,
    gemini_token_components,
    merge_token_components,
    token_components_for_provider,
)

__all__ = [
    "task_telemetry_by_stable_prefix",
    "task_token_telemetry_summary",
    "context_window_observations",
    "task_token_telemetry_to_dict",
    "task_token_telemetry_from_dict",
    "TASK_ATTRIBUTION_HASH_FIELDS",
    "TASK_TOKEN_TELEMETRY_FIELDS",
    "TaskTokenTelemetry",
    "SCHEMA_VERSION",
    "ContextPolicy",
    "LifecycleEventType",
    "NormalizedOutcome",
    "FailureCategory",
    "normalize_outcome",
    "extract_failure_reason",
    "classify_failure_category",
    "infer_retryable",
    "parse_flexible_timestamp",
    "reconcile_attribution_by_task",
    "test_stage_deferrals_for_task",
    "TokenComponents",
    "RuntimeAttribution",
    "ContextLifecycleEvent",
    "ContextPackAttribution",
    "context_pack_attribution_from_event",
    "ProviderContextObservation",
    "ProviderContextClearing",
    "provider_context_by_policy",
    "provider_context_observation_from_event",
    "provider_context_clearing_from_event",
    "provider_context_clearings_from_events",
    "provider_context_observations_from_events",
    "provider_context_window_summary",
    "context_pack_attributions_from_events",
    "context_composition",
    "context_pack_efficiency",
    "retrieval_mode_comparison",
    "TaskEconomicsRecord",
    "ProviderUsageRecord",
    "attribution_to_dict",
    "attribution_from_dict",
    "lifecycle_event_to_dict",
    "lifecycle_event_from_dict",
    "task_economics_to_dict",
    "token_components_to_dict",
    "token_components_from_dict",
    "token_components_total",
    "validate_attribution_dict",
    "claude_token_components",
    "codex_token_components",
    "gemini_token_components",
    "token_components_for_provider",
    "merge_token_components",
    "attach_provider_context_observations",
    "attach_provider_context_clearings",
    "correlate_task_economics",
    "fresh_input_per_successful_task",
    "cache_creation_per_successful_task",
    "cache_read_per_task",
    "failed_retry_token_waste",
    "tokens_per_successful_task",
    "tokens_per_outcome",
    "context_age_vs_token_usage",
    "context_age_vs_failure_rate",
    "compare_context_policies",
    "context_policy_cohort",
    "stratified_failure_rates",
    "unknown_cause_warning",
    "UNKNOWN_FAILURE_CAUSE_WARNING",
    "PARTIAL_UNKNOWN_FAILURE_CAUSE_WARNING",
    "PARTIAL_UNKNOWN_FAILURE_CAUSE_RATE_THRESHOLD",
    "before_after_compact",
    "test_treatment_cohorts",
    "test_treatment_failure_rates",
    "lock_wait_summary",
]
